server:
  compression:
    enabled: true
  # Default port
  port: 8080
  # Enable graceful shutdown - Server will wait for active request to finish
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true
# Spring Configuration
spring:
  application:
    name: mariadb-testcontainers
  jpa:
    # Show sql when spring data jpa performs query
    show-sql: true
  properties:
    hibernate:
      # Format queries
      format_sql: true
# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
mariadb:
  # URL connection to database (appDB is database name)
  jdbc-url: jdbc:mariadb://localhost:3306/appDB
  # MariaDB driver dependency
  driver-class-name: org.mariadb.jdbc.Driver
  # Maximum pool size
  maximum-pool-size: 1
  username: admin
  password: password
